apiVersion: v1
kind: Service
metadata:
  name: kkv-example
  labels:
    app: kkv-example
spec:
  selector:
    type: kontrakt-test
    app: kkv
    test-name: example
  ports:
  - name: envoy
    protocol: TCP
    port: 8080
  - name: kkv
    protocol: TCP
    port: 8090
